"""
Export trained RandomForest + StandardScaler to portable C code.
"""
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import joblib
import numpy as np
from config import MODEL_DIR

# 加载模型
bundle_path = os.path.join(MODEL_DIR, "pose_classifier.joblib")
bundle = joblib.load(bundle_path)
model = bundle["model"]
scaler = bundle["scaler"]

print(f"Model: {type(model).__name__}")
print(f"  n_estimators: {model.n_estimators}")
print(f"  max_depth: {model.max_depth}")
print(f"  n_features: {model.n_features_in_}")
print(f"  classes: {model.classes_}")

# ============================================================
# 导出 StandardScaler 参数
# ============================================================
mean = scaler.mean_
scale = scaler.scale_  # std
n_feat = len(mean)

out_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)), "deploy")
os.makedirs(out_dir, exist_ok=True)

# 1. 导出 scaler 参数为 C 头文件
with open(os.path.join(out_dir, "scaler_params.h"), "w", encoding="utf-8") as f:
    f.write("// Auto-generated StandardScaler parameters\n")
    f.write("// mean_ and scale_ from sklearn.preprocessing.StandardScaler\n")
    f.write(f"#define N_FEATURES {n_feat}\n\n")
    
    f.write(f"static const float scaler_mean[{n_feat}] = {{\n")
    for i in range(0, n_feat, 8):
        vals = ", ".join(f"{v:.10f}f" for v in mean[i:i+8])
        f.write(f"    {vals},\n")
    f.write("};\n\n")
    
    f.write(f"static const float scaler_scale[{n_feat}] = {{\n")
    for i in range(0, n_feat, 8):
        vals = ", ".join(f"{v:.10f}f" for v in scale[i:i+8])
        f.write(f"    {vals},\n")
    f.write("};\n\n")
    
    f.write("static inline void standardize(float *features) {\n")
    f.write("    for (int i = 0; i < N_FEATURES; i++) {\n")
    f.write("        features[i] = (features[i] - scaler_mean[i]) / scaler_scale[i];\n")
    f.write("    }\n")
    f.write("}\n")

print(f"  scaler_params.h written ({n_feat} features)")

# 2. 导出 RandomForest 为 C 代码
# m2cgen 支持多分类 RandomForest
import m2cgen as m2c

c_code = m2c.export_to_c(model, function_name="predict_pose")

with open(os.path.join(out_dir, "random_forest.c"), "w", encoding="utf-8") as f:
    f.write('// Auto-generated RandomForest classifier (C99)\n')
    f.write('// Generated by m2cgen from sklearn.ensemble.RandomForestClassifier\n')
    f.write('#include <math.h>\n')
    f.write('#include "random_forest.h"\n\n')
    f.write(c_code)

# 3. 生成头文件 + 包装函数
with open(os.path.join(out_dir, "random_forest.h"), "w", encoding="utf-8") as f:
    f.write("#ifndef RANDOM_FOREST_H\n")
    f.write("#define RANDOM_FOREST_H\n\n")
    f.write("// 6-class pose classification\n")
    f.write("//  0=walking, 1=sitting, 2=lying, 3=long_sit, 4=abnormal, 5=fall\n\n")
    f.write("// Predict class (0-5) from a float feature array of length N_FEATURES\n")
    f.write("int predict_pose_class(const float *features);\n\n")
    f.write("// m2cgen-exported raw function (returns array of scores)\n")
    f.write("void predict_pose(float *scores, const float *features);\n\n")
    f.write("#endif\n")

with open(os.path.join(out_dir, "random_forest_wrapper.c"), "w", encoding="utf-8") as f:
    f.write("// Wrapper: standardize -> classify -> return class\n")
    f.write('#include "scaler_params.h"\n')
    f.write('#include "random_forest.h"\n')
    f.write('#include <string.h>\n')
    f.write('#include <stdio.h>\n\n')
    f.write("int predict_pose_class(const float *features) {\n")
    f.write("    float norm_features[N_FEATURES];\n")
    f.write("    memcpy(norm_features, features, sizeof(float) * N_FEATURES);\n")
    f.write("    standardize(norm_features);\n")
    f.write("    \n")
    f.write("    float scores[6];\n")
    f.write("    predict_pose(scores, norm_features);\n")
    f.write("    \n")
    f.write("    // argmax\n")
    f.write("    int best_class = 0;\n")
    f.write("    float best_score = scores[0];\n")
    f.write("    for (int i = 1; i < 6; i++) {\n")
    f.write("        if (scores[i] > best_score) {\n")
    f.write("            best_score = scores[i];\n")
    f.write("            best_class = i;\n")
    f.write("        }\n")
    f.write("    }\n")
    f.write("    return best_class;\n")
    f.write("}\n\n")
    f.write("const char* class_name(int cls) {\n")
    f.write("    static const char *names[] = {\n")
    f.write('        "walking", "sitting", "lying", "long_sit", "abnormal", "fall"\n')
    f.write("    };\n")
    f.write("    return (cls >= 0 && cls < 6) ? names[cls] : \"unknown\";\n")
    f.write("}\n")

print(f"  random_forest.c written")
print(f"  random_forest.h written")
print(f"  random_forest_wrapper.c written")
print(f"\n  Output directory: {out_dir}")

# 验证：在 Python 侧对比
print("\nVerifying export...")
X_test = np.random.randn(3, n_feat).astype(np.float32)
X_norm = scaler.transform(X_test)
y_py = model.predict(X_norm)

print(f"  Python  predict: {y_py.tolist()}")
print(f"  Verify by loading C code (compile on target)")

print("\nDone! Files ready for deployment.")
